### ISSUE TITLE
open a default map

### ISSUE THREAD

**Issue by ph98** [SharifAIChallenge/AIC20-Server#6]
hey guys. 
how can i set a default map and run server without having to choose the map? 

setting something in env or passing as a param for java command is ok for me if its possible

**Comment by SinRas** [comment]
@ph98 

guess this is the answer for you

[Configs.java\#L57-L90](https://github.com/SharifAIChallenge/AIC20-Server/blob/26f14494aa25f83d94f4567e7566183d014c8a64/src/main/java/ir/sharif/aichallenge/server/engine/config/Configs.java#L57-L90)

You can generate a config file first (to get a grasp of the configurations you should set). Then set path to the map in the config.

My example is as follows:
```json
{
        "Map": "../maps/1_v1.1.2.map",
        "TeamName0": "Team0",
        "TeamName1": "Team1",
        "TeamName2": "Team2",
        "TeamName3": "Team3",
        "Deploy": "false",
        "ClientsPort": "7099",
        "ClientsConnectionTimeout": "2147483647",
        "UIEnable": "false",
        "UIToken": "00000000000000000000000000000000",
        "UIPort": "7000",
        "UIConnectionTimeout": "2147483647",
        "OCSendToUI": "false",
        "OCSendToFile": "false",
        "OCFilePath": "./game.log"
}
```

you can specify path to the above config file using the following command:
```bash
java -jar server.jar --config=config.json
```

**Comment by taslimisina** [comment]
You must create a system environment variable named "AICMap" and set it's value to be the path of the map file.
